// AUTO-GENERATED by .githooks/post-commit — do not edit.
// Regenerated on every commit / merge / checkout. Gitignored.
window.GIT_VERSION = {
    sha:     '6340708',
    subject: 'feat(cabaret+mummy): independent per-door open/close + mummy-growl SFX',
    branch:  'main',
    builtAt: '2026-06-22T02:52:23Z',
};
